---
title:  "Glimpse of survey responses"
author: "Nick Spyrison"
date:   "09/07/2020"
output:
  html_document:
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F)
library("dplyr")
library("ggplot2")
library("knitr")


prefix <- c("full", "quant", "text")
do_shorten_col_nms <- c(T, F, F)
i_s <- 1:length(prefix)
for(i in i_s) {
  xFilepath = paste0("./data/cleaned_", prefix[i], "_survey_responses_ns2020-07-11.csv")
  .df <- read.csv2(xFilepath, 
                   skip = 1, sep = ",", check.names = F)
  .header <- read.csv2(xFilepath, 
                       skip = 0, sep = ",", nrows = 1)
  .ShortColNames <- colnames(.header)
  if(do_shorten_col_nms[i] == T)
    colnames(.df) <-  .ShortColNames
  .LongColNames  <- as.character(.header)
  .colname_tbl <- data.frame(cbind(.ShortColNames,
                                   .LongColNames,
                                   1:ncol(.header)))
  colnames(.colname_tbl) <- c("ShortName", "LongName", "ColNumber")
  df_nm <- paste0("df_", prefix[i])
  assign(df_nm, .df)
  col_nm <- paste0("colname_tbl_", prefix[i])
  assign(col_nm, .colname_tbl)
  cat(paste0("Assigned ", df_nm, " and ", col_nm, " to the global env. \n"))
}
## EXPECTED init --
f <- df_full
q <- df_quant
t <- df_text
```


```{r}
### Geom bar helper
ns_geom_bar_ord <- function(col_num, ## NUMBER of the column
                            df_obj = q,
                            top_n = 8,
                            do_ord_decr = TRUE) {
  ## Decoded long name
  .col_nm <- colnames(df_obj)[col_num]
  ## Vector of values
  .x <- df_obj[, col_num]
  .x_alt <- .x
  .x_alt[is.na(.x_alt)] <- "<NA>"
  .x_alt[.x_alt == ""] <- "<blank>"
  .cnt_tbl <- sort(table(.x_alt), decreasing = !do_ord_decr)
  .df_cnt <- data.frame(Options = names(.cnt_tbl), 
                        Count = as.numeric(.cnt_tbl))
  
  ## Sum loower options
  .n_rows <- nrow(.df_cnt)
  if(.n_rows > top_n) {
    .df_cnt <- data.frame(
      rbind(.df_cnt[1:top_n, ],
            c("<all other options>", sum(.df_cnt[(top_n + 1):.n_rows, 2]))
      )
    )
  }
    ## Fix disp order after appending <all others>
  .df_cnt$Options <- factor(.df_cnt$Options, levels = unique(.df_cnt$Options))
  
  ## numerator and denominator for response rate
  .n <- length(.x[!is.na(.x)])
  .d <- length(.x)

  ## Create bar chart
  ggplot(.df_cnt, aes(x = Options, y = Count, fill = as.numeric(Count))) + 
    geom_col(stat = "identity") + 
    coord_flip() + 
    ggtitle(paste0("Top ", top_n, " reponses of: ", .col_nm),
            paste0(.n, " non-na obs of ", .d, " respones (", round(100 * .n/.d, 1),"%)")) +
    #scale_x_discrete(limits = rev(levels(.df_cnt$Options))) +
    labs(fill = "Count")
}

library("wordcloud")
library("RColorBrewer")
library("tm")
set.seed(1234) # for reproducibility 
ns_make_wordcloud <- function(col_num, ## NUMBER of the column
                           df_obj = t) {
  ## following: https://towardsdatascience.com/create-a-word-cloud-with-r-bde3e7422e8a
  ## STEP 1: Retrieving the data and uploading the packages
  .x <-  df_obj[, col_num]
  .x_alt <- .x[!is.na(.x)]
  .x_alt <- tolower(.x_alt)
  docs <- Corpus(VectorSource(.x_alt))
  
  ## STEP 2: Clean the text data
  docs <- docs %>%
    tm_map(removeNumbers) %>%
    tm_map(removePunctuation) %>%
    tm_map(stripWhitespace)
  docs <- tm_map(docs, content_transformer(tolower))
  docs <- tm_map(docs, removeWords, stopwords("english"))
  
  ## STEP 3: Create a document-term-matrix
  dtm <- TermDocumentMatrix(docs) 
  matrix <- as.matrix(dtm) 
  words <- sort(rowSums(matrix), decreasing = TRUE) 
  df <- data.frame(word = names(words), freq = words)
  
  ## STEP 4: Generate the word cloud
  ## (set seed outside of for loop)
  .col_nm <- colnames(df_obj)[col_num]
  .title <- paste0(nrow(df), " responses, for: " , .col_nm)
  
  # layout(matrix(c(1, 2), nrow=2), heights=c(1, 4))
  # par(mar=rep(0, 4))
  # plot.new()
  # text(x=0.5, y=0.5, .title, cex = 1)
  cat(.title)
  try(
    wordcloud(words = df$word, freq = df$freq, min.freq = 1,
              max.words=200, random.order = FALSE, rot.per=0.35,
              colors=brewer.pal(8, "Dark2"), main = "Title")
  )
}
```

# Demographics

## World map on Lat/Long


```{r, worldMap}
library("ggmap")
library("maptools")
library("maps")
mapWorld <- borders("world", colour = "gray50", fill = "gray90")

.latlong <- data.frame(lat = as.numeric(f$LocationLatitude),  ## `Location Latitude`
                       long = as.numeric(f$LocationLongitude)) ## `Location Longitude`
.latlong <- .latlong[!is.na(.latlong$lat), ]

.n <- nrow(.latlong)
.d <- nrow(f)

# .xlim <- c(min(.latlong$long) - 40, max(.latlong$long) + 10)
# .ylim <- c(min(.latlong$lat) - 5,  max(.latlong$lat) + 25)

ggplot() + mapWorld +
  theme_minimal() + 
  geom_point(.latlong, mapping = aes(long, lat), alpha = .3, color = "blue") +
  # xlim(.xlim) + ylim(.ylim) + 
  ggtitle("Map of Attendees (alpha=.3)", 
          paste0(.n, " obs of ", .d, " respones (", round(100 * .n/.d, 1),"%)"))
```

### Self reported location -- Q4.1

```{r}
ns_geom_bar_ord(col_num = 12)
```

### Self reported gender -- Q3.1

```{r}
ns_geom_bar_ord(col_num = 7)
```

### Self reported employment/studentship -- Q3.3

```{r}
ns_geom_bar_ord(col_num = 9)
```
# Quantatative fields

```{r}
i_s <- 3:ncol(q)
for(i in i_s)
  print(ns_geom_bar_ord(col_num = i))
```


# Word Cloud on text fields

```{r}
i_s <- 3:ncol(t)
for(i in i_s)
  ns_make_wordcloud(col_num = i)
```

# Candidates for removal

```{r CandidatesForRemoval}
## Based on Progress:
within(f, hist(Progress))
.prog_can <- f[c("ResponseId", "Finished", "Progress")][f$Progress < 100, ]
.o <- order(.prog_can$Progress, decreasing = T)
kable(.prog_can[.o, ])

## Based on Duration:
.dur_can <- data.frame(ResponseId = f$ResponseId,
                       Duration_min = f$Duration..in.seconds. / 60)

ggplot(.dur_can, aes(y = Duration_min)) + geom_boxplot() +
  scale_y_log10() + ylab("Log10, Duration [min]")
.dur_cond <- f$`Duration (in seconds)` < 60 * 3 | f$`Duration (in seconds)` > 60 * 30
.dur_can <- f[c("ResponseId", "Finished", "Duration..in.seconds.")][.dur_cond, ]
.o <- order(.dur_can$Duration..in.seconds., decreasing = T)
cat("Longer than 30 min or less than 3 min: \n")
kable(.dur_can[.o, ])


```

# Overview of the data

```{r glimpse}
try(str(f, nchar.max = 0), silent = T) ## Tibble of dim [120 x 113], 
head(f)             ## Head of Tibble
skimr::skim(f)      ## Break down by column data type
```

